/**
 * Weapon type definitions
 */

/**
 * Weapon types available in the game
 */
export const WeaponType = {
  STANDARD: 'standard',      // Обычный снаряд
  SALVO: 'salvo',            // Залповая система - несколько снарядов из одного дула
  HAZELNUT: 'hazelnut',      // Орешник - один снаряд разделяется на 6 в середине пути
  BOUNCING: 'bouncing',      // Рикошет - отскакивает от поверхности несколько раз
  SHIELD_SINGLE_USE: 'shield_single_use',  // Одноразовый щит
  SHIELD_MULTI_USE: 'shield_multi_use'      // Многоразовый щит
} as const;

export type WeaponType = typeof WeaponType[keyof typeof WeaponType];

/**
 * Fire data from tank
 */
export interface IFireData {
  x: number;
  y: number;
  angle: number;
  power: number;
  weaponType: string;
}

/**
 * Fire plan generated by weapon
 */
export interface IFirePlan {
  projectiles: Array<{
    config: import('./index').IProjectileConfig;
    delay?: number; // Delay in ms before creating this projectile
  }>;
  shotData?: { angle: number; power: number; ownerId: string }; // For first projectile tracking
  playSound?: boolean; // Whether to play fire sound
  clearPreview?: boolean; // Whether to clear trajectory preview
}

/**
 * Explosion configuration
 */
export interface IExplosionConfig {
  radius: number;
  damage: number;
  shape: 'circle' | 'vertical' | 'horizontal';
  shapeRatio: number;
  color?: number;
}

/**
 * Physics configuration
 */
export interface IPhysicsConfig {
  speedMultiplier: number;
  airResistanceMultiplier: number;
}

/**
 * Visual configuration
 */
export interface IVisualConfig {
  color: number;
  explosionColor?: number;
}

